[project]
name = "travel-collector-ai"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "livekit>=1.0.8",
    "livekit-agents>=1.1.1",
    "livekit-plugins-openai>=1.1.1",
    "python-dotenv>=1.1.0",
]
